### ISSUE TITLE
Cannot reinstall after upgrade 18.10 -> 19.04

### ISSUE THREAD

**Issue by SwampFalc** [CTXz/ibm-notes-9.0.1_Ubuntu-16.04_installer#11]
Hi,

I just upgraded my laptop from 18.10 to 19.04 and this uninstalled IBM Notes. Not a big deal, I still have my user directory, except that I cannot reinstall it.

The end of the install process says:

    dpkg-deb: building package 'ibm-notes' in 'ibm-notes-9.0.1.i586.deb'.
    Done patching
    Installing IBM notes 9.0.1
    Reading package lists... Done
    Building dependency tree        
    Reading state information... Done
    Reading state information... Done
    This package is uninstallable
    Dependency is not satisfiable: libgconf2-4
    Failed to install IBM Notes 9.0.1!

However, when checking my system, I do have the package libgconf-2-4 installed (both in 64 and 32 bit versions). But there is that small difference in spelling (the hyphen before the 2)...

I tried simply changing the spelling in your script, but that did not solve it.

**Comment by SwampFalc** [comment]
Okay, so I managed to fix it locally by, indeed, changing libgconf2-4 to libgconf-2-4 in the deb/DEBIAN/control file (where you do the other modifications). Installed fine.

**Comment by CTXz** [comment]
Great!

Sorry that I couldn't provide help earlier, but I'm glad you figured out yourself. I'll update the script as soon as I get to test the changes myself.

Thanks.

**Comment by CTXz** [comment]
Fixed in 6b0a9848394c84564b86ca456a4fac40abeacc02

Thanks for the issue.
