### ISSUE TITLE
Unable to install IBM Notes

### ISSUE THREAD

**Issue by techie-subhadeep** [CTXz/ibm-notes-9.0.1_Ubuntu-16.04_installer#2]
Following error occurred during installation

--2017-11-23 10:47:21--  (try: 7)  http://launchpadlibrarian.net/183708483/libxp6_1.0.2-2_amd64.deb
Connecting to launchpadlibrarian.net (launchpadlibrarian.net)|91.189.89.229|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

**Comment by CTXz** [comment]
This is likely an issue with your connection or [http://launchpadlibrarian.net](http://launchpadlibrarian.net). I assume the issue has been resolved by now as I was able to successfully fetch the libxp6 package just today.
