### ISSUE TITLE
Installing on Ubuntu Desktop 17.10 needs to remove dependency to libpng12-0

### ISSUE THREAD

**Issue by knifehandz** [CTXz/ibm-notes-9.0.1_Ubuntu-16.04_installer#3]
I know this is for 16.04, but just want to let you know for 17.10, only adding:

`sudo sed -i 's/libpng12-0/libpng16-16/g' ./temp_notes_unpacked/DEBIAN/control`

will work fine using your script.

**Comment by CTXz** [comment]
Thanks, I've [updated the patcher](https://github.com/CTXz/ibm-notes-9.0.1_Ubuntu_installer/commit/b75492372f352b019b2150df2430fcb61ebb7110) to work with 17.10 now.
