### ISSUE TITLE
Ubuntu 18.04 Notes is not installed

### ISSUE THREAD

**Issue by carlesfp** [CTXz/ibm-notes-9.0.1_Ubuntu-16.04_installer#7]
I run the installation script and after a while (installation of libraries, etc.) the script ends without having installed anything.
I do not know what information I colud add to solve the problem.
In any case, I will appreciate any help.

```
$ bash Ubuntu-IBM-Notes-9.0.1.sh ibm-notes-9.0.1.i586.deb

(...)
(...)
./usr/share/
./usr/share/applications/
./usr/share/applications/IBMNotes9.0-url.desktop
./usr/share/applications/IBMNotes9.0.desktop
./usr/share/applications/ibm-notes-nsd-hang.desktop
./usr/share/applications/ibm-notes-nsd-kill.desktop
./usr/share/doc/
./usr/share/doc/ibm-notes/
./usr/share/doc/ibm-notes/changelog.Debian.gz
./usr/share/doc/ibm-notes/copyright
./opt/ibm/notes/notes2
dpkg-deb: s'està construint el paquet «ibm-notes» en «ibm-notes-9.0.1.i586.deb».
Done patching
Installing IBM notes 9.0.1
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Traceback (most recent call last):
  File "/usr/bin/gdebi", line 86, in <module>
    if not debi.open(args[0]):
  File "/usr/share/gdebi/GDebi/GDebiCli.py", line 88, in open
    if not self._deb.check():
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 521, in check
    if not self.check_conflicts():
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 357, in check_conflicts
    if self._check_conflicts_or_group(or_group):
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 266, in _check_conflicts_or_group
    depname, in_conflict_checking=True)
  File "/usr/lib/python3/dist-packages/apt/debfile.py", line 125, in _maybe_append_multiarch_suffix
    cand = self._cache[multiarch_pkgname].candidate._cand
AttributeError: 'NoneType' object has no attribute '_cand'
Successfully installed IBM Notes 9.0.1
```

**Comment by kickeupe** [comment]
I just tried installing on Ubuntu 18.04 LTS and I get this error:
# bash Ubuntu-IBM-Notes-9.0.1.sh ibm-notes-9.0.1.i586.deb 
Ubuntu-IBM-Notes-9.0.1.sh: line 7: syntax error near unexpected token `newline'
Ubuntu-IBM-Notes-9.0.1.sh: line 7: `<!DOCTYPE html>'# bash Ubuntu-IBM-Notes-9.0.1.sh ibm-notes-9.0.1.i586.deb

**Comment by kickeupe** [comment]
You need to run as sudo or su and it should work. :)

**Comment by carlesfp** [comment]
Thanks a lot @kickeupe for your suggestion.
The installation script itself asks for superuser access. In any case, I tried to execute the script directly with sudo ... and the results are exactly the same.

**Comment by CTXz** [comment]
Thanks for the feeback, I'll investigate the issue as soon as I found the time to do so

**Comment by CTXz** [comment]
I cannot seem to reproduce that you're experiencing. This appears to be an issue with your installation of gdebi.

Would you mind posting the output of `gdebi --version`?

**Comment by carlesfp** [comment]
Here it is:

```
$ gdebi --version
0.9.5.7+nmu2
```
Thanks for your interest.

**Comment by CTXz** [comment]
Interesting, if I compare it with the output of my VM as well as my host OS:
```
$ gdebi --version
0.9.5.7+nmu1ubuntu3
```

we appear to be running a different version of `gdebi`. Did you install gdebi via the aptitude package manager?

**Comment by carlesfp** [comment]
Yes, this is the version of the package proposed in my system (Ubuntu 18.04.1 LTS):
```
$ apt search gdebi
gdebi/bionic,bionic 0.9.5.7+nmu2 all
  simple tool to view and install deb files - GNOME GUI
gdebi-core/bionic,bionic 0.9.5.7+nmu2 all
  simple tool to install deb files
```
In any case, I tried an alternative to gdebi:
`$ sudo apt install ./ibm-notes-9.0.1.i586.deb`


And It WORKED! Now, I can execute Notes from Ubuntu.


Only one final note: during this process, I read the code of the script and I have in the two wgets. I do not understand the purpose of "temp_install /" added at the end.

And, of course, thank you very much for the installer and your time!

**Comment by CTXz** [comment]
Hmm, good find. I assume I've planned to store the debian pacakges in the temporary installation directory and forgot to add the `-o` option. Likely forgetting about my initial intentions, I then proceeded to write the script to expect the debian packages to be located in the same directory.

Well, whatever the cause be, I'll fix this mistake soon. Thanks.
