### ISSUE TITLE
libgnome-desktop-3-12

### ISSUE THREAD

**Issue by kickeupe** [CTXz/ibm-notes-9.0.1_Ubuntu-16.04_installer#8]
In Ubuntu 18.04 libgnome-desktop-3-17 is used however the installer is looking for libgnome-desktop-3-12.

Even thought it says Successfully installed, just a couple lines before you can see This package is uninstallable

> dpkg-deb: building package 'ibm-notes' in 'ibm-notes-9.0.1.i586.deb'.
Done patching
Installing IBM notes 9.0.1
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
This package is uninstallable
Dependency is not satisfiable: libgnome-desktop-3-12
Successfully installed IBM Notes 9.0.1

**Comment by CTXz** [comment]
I've just tested the script on a brand new Ubuntu 18.04 VM and I'm not sure why the installer is looking for libgnome-desktop-3-12 in your case. The only part where the script downloads a certain version of libgnome-desktop is at the very beginning, which expands to download all versions of libgnome-dekstop presented by `apt` (https://github.com/CTXz/ibm-notes-9.0.1_Ubuntu_installer/blob/master/Ubuntu-IBM-Notes-9.0.1.sh#L31).

Unless IBM has updated the debain package for notes-9.0.1, it should no longer demand libgnome-desktop as a dependency at all after being patched.

Could you post me the full output produced by the patcher (ideally on hastebin)?

**Comment by CTXz** [comment]
I can only assume that this issue has been either resolved or abandoned.

I will gladly reopen upon request.
