### ISSUE TITLE
Installation on Ubuntu with KDE Neon

### ISSUE THREAD

**Issue by andreaferro** [CTXz/ibm-notes-9.0.1_Ubuntu-16.04_installer#9]
Installation on neon-useredition-20181025-0539-amd64 removes neon-desktop package. When reinstalling the desktop package, notes is uninstalled.

**Comment by CTXz** [comment]
Sorry for the late response, I am very busy at the moment.

Just tested the patcher on `neon-devedition-gitunstable-20190114-1049-amd64` and `neon-desktop` remains installed. Does the issue still persist on the useredition?

**Comment by andreaferro** [comment]
I'll try again on the following days
Thank you

**Comment by andreaferro** [comment]
Hi,
had few minutes for another test. It worked just perfect, keeping neon.desktop and notes 9 is up and running. Thank you
Andrea
